# Generated by Django 4.1.7 on 2023-02-28 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                ('isNllb', models.BooleanField(default=False)),
                ('originalLanguage', models.TextField(blank=True, default='')),
                ('targetLanguage', models.TextField(blank=True, default='')),
                ('taggersPerValidation', models.PositiveIntegerField(blank=True, default=1)),
                ('validationThreshold', models.PositiveIntegerField(blank=True, default=50)),
                ('campaignType', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'Translation'), (2, 'Validation')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalItem', models.TextField(default='')),
                ('translatedItem', models.TextField(default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('status', models.TextField(default='translating')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tagger'), (2, 'Manager')], default=1, null=True)),
                ('skills', models.ManyToManyField(blank=True, to='labelingPlatform.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignItemAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, default='translation', null=True)),
                ('cycle', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('translationQuality', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'Good translation'), (2, 'Bad translation')], default=0, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('translation', models.TextField(blank=True, default='')),
                ('answerTime', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labelingPlatform.campaign')),
                ('campaignItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labelingPlatform.campaignitem')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labelingPlatform.profile')),
            ],
        ),
        migrations.AddField(
            model_name='campaignitem',
            name='assignedTagger',
            field=models.ManyToManyField(blank=True, default=None, related_name='itemTaggers', to='labelingPlatform.profile'),
        ),
        migrations.AddField(
            model_name='campaignitem',
            name='assignedTranslator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemTranslator', to='labelingPlatform.profile'),
        ),
        migrations.AddField(
            model_name='campaignitem',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labelingPlatform.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='assignedTaggers',
            field=models.ManyToManyField(blank=True, related_name='campaignTaggers', to='labelingPlatform.profile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='assignedTranslators',
            field=models.ManyToManyField(blank=True, related_name='campaignTranslators', to='labelingPlatform.profile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labelingPlatform.profile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='requiredSkills',
            field=models.ManyToManyField(blank=True, to='labelingPlatform.skill'),
        ),
    ]
